<?php
namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ProductsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        // \DB::table('products')->delete();
        
        \DB::table('products')->insert(array (
            0 => 
            array (
                'id' => 1176,
                'name' => 'PLAGATOX INSECTICIDA LIQUIDO RESIDUAL REPUESTO 500CC',
                'description_short' => 'PLAGATOX INSECTICIDA LIQUIDO RESIDUAL REPUESTO 500CC',
                'description' => NULL,
                'price' => '306748.690000',
                'qty_avaliable' => 100,
                'qty_sold' => 0,
                'qty_view' => 0,
                'user_rating' => '0',
                'qty_min' => 1,
                'qty_max' => 0,
                'keyword' => NULL,
                'status' => 'A',
                'EAN' => NULL,
                'sku' => 27405,
                'promote' => 0,
                'discount' => '0.000000',
                'photo' => NULL,
                'stores_id' => 1,
                'sub_categories_id' => 2,
                'brands_id' => NULL,
                'is_combo' => '0',
                'created_at' => '2020-04-13 16:13:05',
                'updated_at' => '2020-04-13 16:13:05',
            ),
            1 => 
            array (
                'id' => 1177,
                'name' => 'YAYO TOYS SET DE JOYERIA CRISTAL CHIC TPT-810161',
                'description_short' => 'YAYO TOYS SET DE JOYERIA CRISTAL CHIC TPT-810161',
                'description' => NULL,
                'price' => '32900.000000',
                'qty_avaliable' => 100,
                'qty_sold' => 0,
                'qty_view' => 0,
                'user_rating' => '0',
                'qty_min' => 1,
                'qty_max' => 0,
                'keyword' => NULL,
                'status' => 'A',
                'EAN' => NULL,
                'sku' => 25500,
                'promote' => 0,
                'discount' => '0.000000',
                'photo' => NULL,
                'stores_id' => 1,
                'sub_categories_id' => 5,
                'brands_id' => NULL,
                'is_combo' => '0',
                'created_at' => '2020-04-13 16:13:05',
                'updated_at' => '2020-04-13 16:13:05',
            ),
            2 => 
            array (
                'id' => 1178,
                'name' => 'NIVEA VISAGE Q10 LIGHT DAY 50ML',
                'description_short' => 'NIVEA VISAGE Q10 LIGHT DAY 50ML',
                'description' => NULL,
                'price' => '536448.960000',
                'qty_avaliable' => 100,
                'qty_sold' => 0,
                'qty_view' => 0,
                'user_rating' => '0',
                'qty_min' => 1,
                'qty_max' => 0,
                'keyword' => NULL,
                'status' => 'A',
                'EAN' => NULL,
                'sku' => 31830,
                'promote' => 0,
                'discount' => '0.000000',
                'photo' => NULL,
                'stores_id' => 1,
                'sub_categories_id' => 9,
                'brands_id' => NULL,
                'is_combo' => '0',
                'created_at' => '2020-04-13 16:13:05',
                'updated_at' => '2020-04-13 16:13:05',
            ),
            3 => 
            array (
                'id' => 1180,
                'name' => 'SALT VIP INTEGRAL 156GR',
                'description_short' => 'SALT VIP INTEGRAL 156GR',
                'description' => NULL,
                'price' => '99000.000000',
                'qty_avaliable' => 100,
                'qty_sold' => 0,
                'qty_view' => 0,
                'user_rating' => '0',
                'qty_min' => 1,
                'qty_max' => 0,
                'keyword' => NULL,
                'status' => 'A',
                'EAN' => NULL,
                'sku' => 30778,
                'promote' => 0,
                'discount' => '0.000000',
                'photo' => NULL,
                'stores_id' => 1,
                'sub_categories_id' => 9,
                'brands_id' => NULL,
                'is_combo' => '0',
                'created_at' => '2020-04-13 16:13:05',
                'updated_at' => '2020-04-13 16:13:05',
            ),
            4 => 
            array (
                'id' => 1181,
                'name' => 'BLISTER AVENGER 4 FIGURAS B-1906781',
                'description_short' => 'BLISTER AVENGER 4 FIGURAS B-1906781',
                'description' => NULL,
                'price' => '466990.000000',
                'qty_avaliable' => 100,
                'qty_sold' => 0,
                'qty_view' => 0,
                'user_rating' => '0',
                'qty_min' => 1,
                'qty_max' => 0,
                'keyword' => NULL,
                'status' => 'A',
                'EAN' => NULL,
                'sku' => 34618,
                'promote' => 0,
                'discount' => '0.000000',
                'photo' => NULL,
                'stores_id' => 1,
                'brands_id' => NULL,
                'sub_categories_id' => 4,
                'is_combo' => '0',
                'created_at' => '2020-04-13 16:13:05',
                'updated_at' => '2020-04-13 16:13:05',
            ),
            5 => 
            array (
                'id' => 1182,
                'name' => 'NIVEA JABON LIQUIDO DE MANOS HONEY 250ML',
                'description_short' => 'NIVEA JABON LIQUIDO DE MANOS HONEY 250ML',
                'description' => NULL,
                'price' => '44121.420000',
                'qty_avaliable' => 100,
                'qty_sold' => 0,
                'qty_view' => 0,
                'user_rating' => '0',
                'qty_min' => 1,
                'qty_max' => 0,
                'keyword' => NULL,
                'status' => 'A',
                'EAN' => NULL,
                'sku' => 32967,
                'promote' => 0,
                'discount' => '0.000000',
                'photo' => NULL,
                'stores_id' => 1,
                'brands_id' => NULL,
                'is_combo' => '0',
                'sub_categories_id' => 15,
                'created_at' => '2020-04-13 16:13:05',
                'updated_at' => '2020-04-13 16:13:05',
            ),
            6 => 
            array (
                'id' => 1183,
                'name' => 'VAZA ACEITE GIRASOL PET 850ML',
                'description_short' => 'VAZA ACEITE GIRASOL PET 850ML',
                'description' => NULL,
                'price' => '171529.410000',
                'qty_avaliable' => 100,
                'qty_sold' => 0,
                'qty_view' => 0,
                'user_rating' => '0',
                'qty_min' => 1,
                'qty_max' => 0,
                'keyword' => NULL,
                'status' => 'A',
                'EAN' => NULL,
                'sku' => 34515,
                'promote' => 0,
                'discount' => '0.000000',
                'photo' => NULL,
                'stores_id' => 1,
                'sub_categories_id' => 1,
                'brands_id' => NULL,
                'is_combo' => '0',
                'created_at' => '2020-04-13 16:13:05',
                'updated_at' => '2020-04-13 16:13:05',
            ),
            7 => 
            array (
                'id' => 1184,
                'name' => 'QUIDY MAYONESA 180GR',
                'description_short' => 'QUIDY MAYONESA 180GR',
                'description' => NULL,
                'price' => '100119.290000',
                'qty_avaliable' => 100,
                'qty_sold' => 0,
                'qty_view' => 0,
                'user_rating' => '0',
                'qty_min' => 1,
                'qty_max' => 0,
                'keyword' => NULL,
                'status' => 'A',
                'EAN' => NULL,
                'sku' => 34540,
                'promote' => 0,
                'discount' => '0.000000',
                'photo' => NULL,
                'stores_id' => 1,
                'brands_id' => NULL,
                'is_combo' => '0',
                'sub_categories_id' => 3,
                'created_at' => '2020-04-13 16:13:05',
                'updated_at' => '2020-04-13 16:13:05',
            ),
            8 => 
            array (
                'id' => 1185,
                'name' => 'ALIDENT CREMA DENTAL GEL VERDE ALIENTO FRESCO 100GR',
                'description_short' => 'ALIDENT CREMA DENTAL GEL VERDE ALIENTO FRESCO 100GR',
                'description' => NULL,
                'price' => '164057.140000',
                'qty_avaliable' => 100,
                'qty_sold' => 0,
                'qty_view' => 0,
                'user_rating' => '0',
                'qty_min' => 1,
                'qty_max' => 0,
                'keyword' => NULL,
                'status' => 'A',
                'EAN' => NULL,
                'sku' => 34740,
                'promote' => 0,
                'discount' => '0.000000',
                'photo' => NULL,
                'stores_id' => 1,
                'brands_id' => NULL,
                'is_combo' => '0',
                'sub_categories_id' => 9,
                'created_at' => '2020-04-13 16:13:05',
                'updated_at' => '2020-04-13 16:13:05',
            ),
            9 => 
            array (
                'id' => 1186,
                'name' => 'MARY CREMA ARROZ 450GR',
                'description_short' => 'MARY CREMA ARROZ 450GR',
                'description' => NULL,
                'price' => '40802.200000',
                'qty_avaliable' => 100,
                'qty_sold' => 0,
                'qty_view' => 0,
                'user_rating' => '0',
                'qty_min' => 1,
                'qty_max' => 0,
                'keyword' => NULL,
                'status' => 'A',
                'EAN' => NULL,
                'sku' => 9492,
                'promote' => 0,
                'discount' => '0.000000',
                'photo' => NULL,
                'stores_id' => 1,
                'brands_id' => NULL,
                'is_combo' => '0',
                'sub_categories_id' => 10,
                'created_at' => '2020-04-13 16:13:05',
                'updated_at' => '2020-04-13 16:13:05',
            ),
            10 => 
            array (
                'id' => 1069,
                'name' => 'VALE LIMPIADOR ANTIBACTERIAL FRUTOS ROJOS 1LT',
                'description_short' => 'VALE LIMPIADOR ANTIBACTERIAL FRUTOS ROJOS 1LT',
                'description' => NULL,
                'price' => '109909.350000',
                'qty_avaliable' => 100,
                'qty_sold' => 0,
                'qty_view' => 0,
                'user_rating' => '0',
                'qty_min' => 1,
                'qty_max' => 0,
                'keyword' => NULL,
                'status' => 'A',
                'EAN' => NULL,
                'sku' => 23624,
                'promote' => 0,
                'discount' => '0.000000',
                'photo' => NULL,
                'stores_id' => 1,
                'brands_id' => NULL,
                'is_combo' => '0',
                'sub_categories_id' => 11,
                'created_at' => '2020-04-13 16:13:05',
                'updated_at' => '2020-04-13 16:13:05',
            ),
            11 => 
            array (
                'id' => 1169,
                'name' => 'SOFT BLASTER PISTOLA DE DARDOS B-1906773',
                'description_short' => 'SOFT BLASTER PISTOLA DE DARDOS B-1906773',
                'description' => NULL,
                'price' => '1044990.000000',
                'qty_avaliable' => 100,
                'qty_sold' => 0,
                'qty_view' => 0,
                'user_rating' => '0',
                'qty_min' => 1,
                'qty_max' => 0,
                'keyword' => NULL,
                'status' => 'A',
                'EAN' => NULL,
                'sku' => 34607,
                'promote' => 0,
                'discount' => '0.000000',
                'photo' => NULL,
                'stores_id' => 1,
                'brands_id' => NULL,
                'is_combo' => '0',
                'sub_categories_id' => 12,
                'created_at' => '2020-04-13 16:13:05',
                'updated_at' => '2020-04-13 16:13:05',
            ),
            12 => 
            array (
                'id' => 1170,
                'name' => 'ALOVAYS TAOLLAS ULTRAFINA CON GEL 10UND',
                'description_short' => 'ALOVAYS TAOLLAS ULTRAFINA CON GEL 10UND',
                'description' => NULL,
                'price' => '6662.540000',
                'qty_avaliable' => 100,
                'qty_sold' => 0,
                'qty_view' => 0,
                'user_rating' => '0',
                'qty_min' => 1,
                'qty_max' => 0,
                'keyword' => NULL,
                'status' => 'A',
                'EAN' => NULL,
                'sku' => 33136,
                'promote' => 0,
                'discount' => '0.000000',
                'photo' => NULL,
                'stores_id' => 1,
                'brands_id' => NULL,
                'is_combo' => '0',
                'sub_categories_id' => 13,
                'created_at' => '2020-04-13 16:13:05',
                'updated_at' => '2020-04-13 16:13:05',
            ),
            13 => 
            array (
                'id' => 1173,
                'name' => 'FIT ANTIBACTERIAL BIO LIMON 1.5L',
                'description_short' => 'FIT ANTIBACTERIAL BIO LIMON 1.5L',
                'description' => NULL,
                'price' => '308725.710000',
                'qty_avaliable' => 100,
                'qty_sold' => 0,
                'qty_view' => 0,
                'user_rating' => '0',
                'qty_min' => 1,
                'qty_max' => 0,
                'keyword' => NULL,
                'status' => 'A',
                'EAN' => NULL,
                'sku' => 34162,
                'promote' => 0,
                'discount' => '0.000000',
                'photo' => NULL,
                'stores_id' => 1,
                'brands_id' => NULL,
                'sub_categories_id' => 14,
                'is_combo' => '0',
                'created_at' => '2020-04-13 16:13:05',
                'updated_at' => '2020-04-13 16:13:05',
            ),
            14 => 
            array (
                'id' => 1174,
                'name' => 'FRESCALIDAD DEDITOS YUCA 1KG',
                'description_short' => 'FRESCALIDAD DEDITOS YUCA 1KG',
                'description' => NULL,
                'price' => '140714.280000',
                'qty_avaliable' => 100,
                'qty_sold' => 0,
                'qty_view' => 0,
                'user_rating' => '0',
                'qty_min' => 1,
                'qty_max' => 0,
                'keyword' => NULL,
                'status' => 'A',
                'EAN' => NULL,
                'sku' => 27234,
                'promote' => 0,
                'discount' => '0.000000',
                'photo' => NULL,
                'stores_id' => 1,
                'brands_id' => NULL,
                'sub_categories_id' => 16,
                'is_combo' => '0',
                'created_at' => '2020-04-13 16:13:05',
                'updated_at' => '2020-04-13 16:13:05',
            ),
            15 => 
            array (
                'id' => 678,
                'name' => 'FIT LIMPIADOR BIO NARANJA 940ML',
                'description_short' => 'FIT LIMPIADOR BIO NARANJA 940ML',
                'description' => NULL,
                'price' => '240120.000000',
                'qty_avaliable' => 100,
                'qty_sold' => 0,
                'qty_view' => 0,
                'user_rating' => '0',
                'qty_min' => 1,
                'qty_max' => 0,
                'keyword' => NULL,
                'status' => 'A',
                'EAN' => NULL,
                'sku' => 34156,
                'promote' => 0,
                'discount' => '0.000000',
                'photo' => NULL,
                'stores_id' => 1,
                'brands_id' => NULL,
                'sub_categories_id' => 17,
                'is_combo' => '0',
                'created_at' => '2020-04-13 16:13:05',
                'updated_at' => '2020-04-13 16:13:05',
            ),
            
        ));
        
        
        
    }
}